version: "3.8"

services:
  psql-db:
    image: postgres:latest
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database-pg
    ports:
      - '5432:5432'

  employees:
    container_name: employees_app
    build:
      context: .
      dockerfile: Dockerfile
    image: employees:v1
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/database-pg
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
